"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import socket
import logging
import json
from pathlib import Path
from decouple import config
from celery.schedules import crontab
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-pxng&q)bg#w&z#rtcf3rdy5$fe_rh&b*gpcgu&_s228wjo4q$a",
    cast=str,
)

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_celery_beat",
    "debug_toolbar",
    "django_summernote",
    "mptt",
    "account.apps.AccountConfig",
    "website.apps.WebsiteConfig",
    "blog.apps.BlogConfig",
    "common.apps.CommonConfig",
    "shop.apps.ShopConfig",
    "review.apps.ReviewConfig",
    "cart.apps.CartConfig",
    "order.apps.OrderConfig",
    "payment.apps.PaymentConfig",
    "coupon.apps.CouponConfig",
    "dashboard.apps.DashboardConfig",
    "wishlist.apps.WishlistConfig",
    "recently_viewed.apps.RecentlyViewedConfig",
    "notifications.apps.NotificationsConfig",
    "contact.apps.ContactConfig",
    "faq.apps.FaqConfig",
    "pages.apps.PagesConfig",
    "newsletter.apps.NewsletterConfig",
    "banner.apps.BannerConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "core.middleware.CorrelationIdMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart_processor",
                "shop.context_processors.categories_processor",
                "shop.context_processors.search_log_processor",
                "notifications.context_processors.new_messages_count_processor",
                "pages.context_processors.static_pages_processor",
                "account.context_processors.user_processor",
                "website.context_processors.site_info_processor",
                "website.context_processors.site_resource_socials_processor",
                "website.context_processors.site_resource_licenses_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("NAME", default="name", cast=str),
        "USER": config("USER", default="user", cast=str),
        "PASSWORD": config("PASSWORD", default="password", cast=str),
        "HOST": config("HOST", default="db", cast=str),
        "PORT": config("PORT", default=5432, cast=int),
    }
}

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "statics"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CustomUser configurations

AUTH_USER_MODEL = "account.CustomUser"


LOGIN_URL = "/account/phone-auth/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"



# logging configuration


class JSONFormatter(logging.Formatter):
    def format(self, record):
        log_record = {
            "time": self.formatTime(record, self.datefmt),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }

        if hasattr(record, "task_name"):
            log_record["task_name"] = record.task_name

        if hasattr(record, "correlation_id"):
            log_record["correlation_id"] = record.correlation_id

        extras = {
            k: self._safe_value(v)
            for k, v in record.__dict__.items()
            if k not in logging.LogRecord.__dict__
            and k
            not in (
                "msg",
                "args",
                "levelname",
                "levelno",
                "pathname",
                "filename",
                "module",
                "exc_info",
                "exc_text",
                "stack_info",
                "lineno",
                "funcName",
                "created",
                "msecs",
                "relativeCreated",
                "thread",
                "threadName",
                "processName",
                "process",
                "message",
                "task_name",
                "taskName",
                "correlation_id",
            )
        }
        if extras:
            log_record["extra"] = extras

        return json.dumps(log_record, ensure_ascii=False)

    def _safe_value(self, value):
        try:
            json.dumps(value)
            return value
        except TypeError:
            return str(value)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": JSONFormatter,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "level": "ERROR",  
        },
        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/security.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "json",
        },
        "auth_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/auth.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "json",
        },
        "otp_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/otp.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "json",
        },
        "payment_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/payment.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "json",
        },
        "apps_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/apps.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],  
            "level": "ERROR",
        },
        "security": {
            "handlers": ["security_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "authentication": {
            "handlers": ["auth_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "otp": {
            "handlers": ["otp_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "payment": {
            "handlers": ["payment_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": {
            "handlers": ["apps_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")


# OTP configuration
OTP_SERVICE_API_KEY = "your_api_key"
OTP_SERVICE_URL = "https://sms.example.com/send"
OTP_CODE_LENGTH = 4
OTP_EXPIRY_SECONDS = 120


# debug toolbar configuration
if DEBUG:
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + [
        "127.0.0.1",
        "10.0.2.2",
    ]

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }


# payment gateway settings
MERCHANT_ID = config(
    "MERCHANT_ID", default="4ced0a1e-4ad8-4309-9668-3ea3ae8e8897"
)
# URL configuration
ROOT_URLCONF = "core.urls"

PAYMENT_SANDBOX_MODE = True

# Site configuration
SITE_ID = 1


CELERY_BEAT_SCHEDULE = {
    "cancel-expired-orders": {
        "task": "order.tasks.cancel_expired_pending_orders",
        "schedule": timedelta(minutes=1),
    },
}
